<!-- ====== REGISTER PAGE ====== -->
<style>
.auth-page { background: #ffffff !important; }
#particles-js { display: none !important; }
.auth-clean-card {
    width: 100%; max-width: 650px;
    margin: 0 auto;
    padding: 3rem 1.5rem;
    text-align: center;
}
.auth-headline {
    font-size: 3rem;
    font-weight: 900;
    color: #111111;
    letter-spacing: -0.04em;
    line-height: 1.1;
    margin-bottom: 0.5rem;
}
.auth-headline-accent {
    color: #CC0000;
}
.auth-subhead {
    font-size: 1.15rem;
    color: #555555;
    font-weight: 500;
    margin-bottom: 2.5rem;
}
.auth-clean-input {
    background-color: #f9f9f9 !important;
    border: 1px solid #eeeeee !important;
    border-radius: 12px !important;
    padding-top: 1.25rem !important;
    padding-bottom: 1.25rem !important;
    padding-right: 1rem !important;
    padding-left: 1.25rem; /* Removed !important to allow dynamic padding-left from intl-tel-input */
    font-size: 1.1rem !important;
    font-weight: 500 !important;
    color: #111111 !important;
    height: auto !important;
    box-shadow: none !important;
    transition: all 0.2s !important;
}
.auth-clean-input::placeholder {
    color: #666666 !important;
    opacity: 1 !important;
}
.auth-clean-input:focus {
    background-color: #ffffff !important;
    border-color: #CC0000 !important;
    box-shadow: 0 0 0 4px rgba(204,0,0,0.1) !important;
}
/* Prevent browser autofill from breaking style consistency */
.auth-clean-input:-webkit-autofill,
.auth-clean-input:-webkit-autofill:hover, 
.auth-clean-input:-webkit-autofill:focus, 
.auth-clean-input:-webkit-autofill:active {
    -webkit-box-shadow: 0 0 0 1000px #f9f9f9 inset !important;
    -webkit-text-fill-color: #111111 !important;
    transition: background-color 5000s ease-in-out 0s !important;
}
/* Fallback for telephone input flag/dial-code wrapping container */
.iti input[type="tel"].auth-clean-input,
.intl-tel-input input[type="tel"].auth-clean-input {
    padding-left: 85px; /* Standard fallback if dynamic script padding doesn't fire */
}
/* Style checkboxes properly with high contrast and custom border */
.form-check-input {
    border: 1.5px solid #cccccc !important;
    background-color: #ffffff !important;
    border-radius: 6px !important;
    width: 1.2em !important;
    height: 1.2em !important;
    cursor: pointer !important;
    margin-top: 0.15em !important;
    transition: all 0.2s !important;
}
.form-check-input:checked {
    background-color: #CC0000 !important;
    border-color: #CC0000 !important;
}
.form-check-input:focus {
    box-shadow: 0 0 0 3px rgba(204,0,0,0.15) !important;
    border-color: #CC0000 !important;
}
.auth-clean-btn {
    background: #CC0000;
    color: #ffffff;
    font-weight: 700;
    font-size: 1.15rem;
    border-radius: 50rem;
    padding: 1rem 2rem;
    border: none;
    transition: all 0.2s;
    box-shadow: 0 8px 24px rgba(204,0,0,0.25);
    width: 100%;
}
.auth-clean-btn:hover {
    background: #AA0000;
    transform: translateY(-2px);
    box-shadow: 0 12px 32px rgba(204,0,0,0.3);
    color: #ffffff;
}
.auth-clean-tabs {
    display: inline-flex;
    background: #f5f5f5;
    border-radius: 50rem;
    padding: 0.25rem;
    margin-bottom: 2rem;
}
.auth-clean-tab {
    padding: 0.6rem 1.5rem;
    font-weight: 600;
    font-size: 0.95rem;
    color: #555555;
    border-radius: 50rem;
    text-decoration: none;
    transition: all 0.2s;
}
.auth-clean-tab.active {
    background: #ffffff;
    color: #111111;
    box-shadow: 0 2px 8px rgba(0,0,0,0.05);
}
.auth-clean-tab:hover:not(.active) {
    color: #111111;
}
.section-title {
    text-align: left;
    font-size: 0.85rem;
    font-weight: 700;
    color: #888888;
    text-transform: uppercase;
    letter-spacing: 1px;
    margin: 1.5rem 0 1rem;
}
.custom-field-label {
    display: block;
    text-align: left;
    font-size: 0.85rem;
    font-weight: 600;
    color: #555;
    margin-bottom: 0.5rem;
}
.auth-clean-card .form-control {
    /* For custom fields dynamically generated by WHMCS */
    border-radius: 12px !important;
    background-color: #f9f9f9 !important;
    border: 1px solid #eeeeee !important;
    padding: 1.25rem 1rem !important;
    font-size: 1.1rem !important;
    font-weight: 500 !important;
    color: #111111 !important;
    height: auto !important;
    box-shadow: none !important;
    transition: all 0.2s !important;
}
.auth-clean-card .form-control:focus {
    background-color: #ffffff !important;
    border-color: #CC0000 !important;
    box-shadow: 0 0 0 4px rgba(204,0,0,0.1) !important;
}
</style>

<div class="auth-clean-card">
    <div style="margin-bottom:2rem;">
        <span style="display:inline-flex; align-items:center; gap:0.5rem; background:rgba(204,0,0,0.08); color:#CC0000; padding:0.4rem 1rem; border-radius:50rem; font-size:0.75rem; font-weight:700; text-transform:uppercase; letter-spacing:1px;">
            <i class="fas fa-rocket"></i> Get Started
        </span>
    </div>

    <h1 class="auth-headline">Create an <span class="auth-headline-accent">Account.</span></h1>
    <p class="auth-subhead">Join SNBD HOST and deploy in seconds.</p>

    <div class="auth-clean-tabs">
        <a href="{$WEB_ROOT}/login.php" class="auth-clean-tab">Sign In</a>
        <a href="{$WEB_ROOT}/register.php" class="auth-clean-tab active">Create Account</a>
    </div>

    {if $errormessage}
        <div class="alert alert-danger py-2 text-center small mb-4 rounded-3 border-0" style="background:rgba(204,0,0,0.1); color:#CC0000; font-weight:600;">
            <i class="fas fa-exclamation-circle me-1"></i>{$errormessage}
        </div>
    {/if}

    <form method="post" action="{$WEB_ROOT}/register.php" id="frmRegister" class="needs-validation login-form text-start" role="form">
        <input type="hidden" name="register" value="true" />
        <input type="hidden" name="token" value="{$token}" />
        
        <div class="section-title">Personal Details</div>
        <div class="row g-3 mb-3">
            <div class="col-md-6">
                <input type="text" name="firstname" class="form-control auth-clean-input" id="inputFirstName" placeholder="{$LANG.clientareafirstname}" value="{$clientfirstname}" required>
            </div>
            <div class="col-md-6">
                <input type="text" name="lastname" class="form-control auth-clean-input" id="inputLastName" placeholder="{$LANG.clientarealastname}" value="{$clientlastname}" required>
            </div>
        </div>

        <div class="row g-3 mb-3">
            <div class="col-md-6">
                <input type="email" name="email" class="form-control auth-clean-input" id="inputEmail" placeholder="{$LANG.clientareaemail}" value="{$clientemail}" required>
            </div>
            <div class="col-md-6">
                <input type="tel" name="phonenumber" class="form-control auth-clean-input" id="inputPhone" placeholder="{$LANG.clientareaphonenumber}" value="{$clientphonenumber}" required>
            </div>
        </div>
        
        {if $showCompanyOrTax}
        <div class="row g-3 mb-3">
            <div class="col-md-6">
                <input type="text" name="companyname" class="form-control auth-clean-input" id="inputCompanyName" placeholder="{$LANG.clientareacompanyname} (Optional)" value="{$clientcompanyname}">
            </div>
            {if $taxIdEnabled}
            <div class="col-md-6">
                <input type="text" name="tax_id" class="form-control auth-clean-input" id="inputTaxId" placeholder="{$LANG.clientareataxid}" value="{$clienttaxid}">
            </div>
            {/if}
        </div>
        {else}
        <div class="mb-3">
            <input type="text" name="companyname" class="form-control auth-clean-input" id="inputCompanyName" placeholder="{$LANG.clientareacompanyname} (Optional)" value="{$clientcompanyname}">
        </div>
        {/if}

        <div class="section-title">Billing Address</div>
        <div class="row g-3 mb-3">
            <div class="col-md-6">
                <input type="text" name="address1" class="form-control auth-clean-input" id="inputAddress1" placeholder="{$LANG.clientareaaddress1}" value="{$clientaddress1}" required>
            </div>
            <div class="col-md-6">
                <input type="text" name="address2" class="form-control auth-clean-input" id="inputAddress2" placeholder="{$LANG.clientareaaddress2} (Optional)" value="{$clientaddress2}">
            </div>
        </div>
        
        <div class="row g-3 mb-3">
            <div class="col-md-4">
                <input type="text" name="city" class="form-control auth-clean-input" id="inputCity" placeholder="{$LANG.clientareacity}" value="{$clientcity}" required>
            </div>
            <div class="col-md-4">
                <input type="text" name="state" class="form-control auth-clean-input" id="inputState" placeholder="{$LANG.clientareastate}" value="{$clientstate}" required>
            </div>
            <div class="col-md-4">
                <input type="text" name="postcode" class="form-control auth-clean-input" id="inputPostcode" placeholder="{$LANG.clientareapostcode}" value="{$clientpostcode}" required>
            </div>
        </div>
        
        <div class="mb-3">
            <select name="country" class="form-select auth-clean-input" id="inputCountry">
                {foreach $clientcountries as $countryCode => $countryName}
                    <option value="{$countryCode}"{if (!$clientcountry && $countryCode eq $defaultCountry) || ($countryCode eq $clientcountry)} selected="selected"{/if}>
                        {$countryName}
                    </option>
                {/foreach}
            </select>
        </div>
        
        {if $customfields}
            <div class="section-title">Additional Information</div>
            {foreach $customfields as $customfield}
                <div class="mb-3 text-start">
                    <label class="custom-field-label" for="customfield{$customfield.id}">{$customfield.name}</label>
                    <div class="control-group">
                        {$customfield.input} 
                        {if $customfield.description}<div class="text-muted small mt-1">{$customfield.description}</div>{/if}
                    </div>
                </div>
            {/foreach}
        {/if}

        {if $securityquestions}
            <div class="section-title">Security Question</div>
            <div class="mb-3">
                <select name="securityqid" class="form-select auth-clean-input" id="inputSecurityQid">
                    {foreach $securityquestions as $question}
                        <option value="{$question.id}">{$question.question}</option>
                    {/foreach}
                </select>
            </div>
            <div class="mb-3">
                <input type="text" name="securityqans" class="form-control auth-clean-input" id="inputSecurityAns" placeholder="Security Answer" required>
            </div>
        {/if}
        
        <div class="section-title">Account Security</div>
        <div class="row g-3 mb-4">
            <div class="col-md-6">
                <input type="password" name="password" class="form-control auth-clean-input" id="inputPassword" placeholder="{$LANG.clientareapassword}" autocomplete="off" required>
            </div>
            <div class="col-md-6">
                <input type="password" name="password2" class="form-control auth-clean-input" id="inputPasswordConfirm" placeholder="{$LANG.confirmpassword}" autocomplete="off" required>
            </div>
        </div>

        {if $showMarketingEmailOptIn}
            <div class="form-check mb-3 px-2 text-start d-flex align-items-start gap-2">
                <input type="checkbox" name="marketingoptin" class="form-check-input" value="1" id="marketingoptin" {if $marketingEmailOptIn}checked{/if}>
                <label class="form-check-label small fw-semibold ms-1" for="marketingoptin" style="margin-top: 2px; color: #444444 !important; line-height: 1.3;">
                    {$marketingEmailOptInMessage|default:"Subscribe to our newsletter for updates, promotions, and special offers."}
                </label>
            </div>
        {/if}

        {if $accepttos}
            <div class="form-check mb-4 px-2 text-start d-flex align-items-start gap-2">
                <input type="checkbox" name="accepttos" class="form-check-input" id="accepttos" required>
                <label class="form-check-label small fw-semibold ms-1" for="accepttos" style="margin-top: 2px; color: #444444 !important; line-height: 1.3;">
                    {$LANG.ordertosagreement} <a href="{$tosurl}" target="_blank" class="text-dark fw-bold text-decoration-none">{$LANG.ordertos}</a>
                </label>
            </div>
        {/if}

        {if $captcha}
            <div class="mb-4 d-flex justify-content-center">
                {include file="$template/includes/captcha.tpl"}
            </div>
        {/if}

        <button type="submit" class="auth-clean-btn mt-2">
            Create Account Now <i class="fas fa-arrow-right ms-2" style="font-size:0.9em;"></i>
        </button>
    </form>
    
    <div class="mt-5 text-muted small fw-medium">
        By continuing, you agree to SNBD HOST's Terms of Service and Privacy Policy.
    </div>
</div>
